### ISSUE TITLE
Ta fram 6 frågor vardera för till frågeformulär feedback på MYH.se

### ISSUE THREAD

**Issue by Bjorn77Karlsson** [chas-academy/u02-redesign-fulhackarna#15]
Ta fram 6 frågor vardera för att få feedback på befintlig design, som sedan skall sammanställas i ett frågeformulär till 
1. Företag/organisationer, 
2. Utbildningsamordnare, 
3. Studenter 

(2 frågor till varje kategori)

**Comment by Bjorn77Karlsson** [comment]
Klar med mina frågor:

---Företag/Organisationer---
- Vad är din roll på ditt företag?
- Var söker du, när du vill hitta utbildningssamordnare som kan utbilda er personal... Varför?
- Vad är ditt första intryck när du besöker denna sida?
- Ge en betyg 1-10 (där 10 är bästa betyg) för följande när du besöker denna sida.
	- Användarvänlig
	- Tydlighet vem/vilka sidan vänder sig mot
	- Pedagogisk
	- Lätthet att hitta rätt
- Vad förväntar du dig av en myndighets-webbsida?

---Utbildningssamordnare---
- I vilket avseende besöker du/skulle kunna besöka www.myh.se
- Vad anser du att skulle kunna bli bättre med sidan av design, innehåll och användarvänlighet?

---Studerande---
- Vad och var studerar du?
- Vad är ditt först intryck av www.myh.se?
- Leta dig fram till att lämna en synpunkt på en YH-utbildning!
- Vad var bra / dåligt för att hamna rätt och skicka in dina synpunkter?
- Hur lätt/svårt var det att hitta till utbildningar att söka?
- Tycker du denna www.myh.se fyller sin roll som ansvarig myndighet för din utbildning.
- Vad är ditt allmänna intryck av www.myh.se

**Comment by LinusUnghammar** [comment]
Till student:
- Vad tror du är anledningen till att denna sida existerar?
- Hur ser du på upplägget av strukturen på denna sida?

Till utbildningsamordnare:
- vad är ditt första intryck av denna sida? 
- Vad tycker du saknas på denna sida?

Till företag/organisation:
- Hittar du snabbt det du söker?
- Vad får du ut av denna sida?

**Comment by OskarFindahl** [comment]
Har förslag på uppgifter man kan ge målgrupperna. Sedan kan man ställa följdfrågor som Var det lätt att hitta? Vad var bra/dåligt? Hur var processen tidsmässigt? 

För företag organisationer:
- Hitta utbildningar inom bygg att samarbeta med.
- Finn information om ledningsgruppsarbete och hitta kontaktuppgifter för valfri YH-skola.

För utbildningssamordnare:
- Hitta den senaste kvalitetsgranskningsrapporten för tolkutbildningar.
- Hitta checklistan för att starta en YH-utbildning. 

För studenter:
- Hitta en utbildning du är intresserad av.
- Hitta formuläret för att anmäla brister i en utbildning.

**Comment by jamil-source** [comment]
Till student:

- Vad skulle du som student vilja ha utifrån hemsidan?
- Tycker du att information är lätt/svårt att hitta?

Till utbildningsamordnare:

- Vart i myh.se dras din blick till?
- Vad skulle du som utbildningsamordare vilja få ut av hemsidan?

Till företag/organisation:

- Hur känner du när du scrollar igenom hemsidan?
- Skulle ditt företag kunna ha en sådan layout?

**Comment by Talica2005** [comment]
**Till student:**
- Är det lätt att navigera på webbplatsen?
- Vilka webbplatser gillar du och varför?
- Vad tycker du om eller tycker inte om design? Hur ser du webbplatsen?

**Till företag/organisation:**
- Vad är den första åtgärden du skulle vidta på den webbsida?
- Finns det några speciella funktioner som borde finnas på webbplatsen?
- Varför bestämde du för att använda vår webbplats?

**Till utbildningsamordnare:**
- Behöver besökare något speciellt? Mobilversion av webbplatsen? Stöd för flera språk? Större teckenstorlek för enklare läsbarhet?
- Om du tillbringar två minuter på webbplats, vad ska du definitivt se (3 saker, i prioritetsordning)?
