### ISSUE TITLE
Ställer frågor till sin mamma också som är rektor.

### ISSUE THREAD

**Issue by Bjorn77Karlsson** [chas-academy/u02-redesign-fulhackarna#22]

**Comment by LinusUnghammar** [comment]
- Vad är ditt första intryck av denna sida? 
Den ser stel och tråkig ut, innehållet har hamnat alldeles för centralt på sidan. 
Man ser tydligt att det är en myndighetssida.

- Vad tror du är anledningen till att denna sida existerar?
För att lagra viktig info, så att studiesammordnare enkelt och snabbt
kan ta reda på saker på egen hand utan att behöva få tag i någon.

- Vart börjar du nånstans?
Skummar igenom startsidan, så man kan se lite enkelt vart man har allting. 

- Hur skulle du gå tillväga om du letar efter något särskilt?
Använda sökfunktionen.

- Är det enkelt att hitta det du söker?
rätt enkelt, men utan sökfunktionen hade det varit svårare. 

- Vart på sidan dras din blick?
Den rörliga delen, och menyn med gula färger (som även är jobbigt gul).  

- Vad skulle du vilja få ut av denna sida?
Om man går in på myh så gör man det inte för att det är roligt. 
utan man gör det för att man vill få svar på nånting. 
Så det man önskar med en sån här sida är att den ska vara heltäckande.
