### ISSUE TITLE
Tryout Card 1

### ISSUE THREAD

**Issue by Bjorn77Karlsson** [chas-academy/u02-redesign-fulhackarna#4]
[U02 Grupp 2 - Sprint 1 - Mötesdokumenation 20201007.txt](https://github.com/chas-academy/u02-redesign-fulhackarna/files/5354731/U02.Grupp.2.-.Sprint.1.-.Motesdokumenation.20201007.txt)
![2](https://user-images.githubusercontent.com/70579206/95580270-5cb86700-0a37-11eb-89ea-b68341a5e696.jpg)

# Titelnamn = h1 
## Titelnamn = h2 
o.s.v.

**fet text**

*kursiv text*

Create card and how to do it also what people I shall car this task with.

- [ ] Test checkbox

- Only list

- [x] Checkad lista

länk extern [Wikipedia](url till sida)

bild ![Bilden föreställer....](url till bild)

@SkySails # #4 #2

**Comment by SkySails** [comment]
Beautifully done! Closing since this was made for demo purposes.

**Comment by SkySails** [comment]
Beautifully done! Closing since this was made for demo purposes.
